name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test on Deno
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: maximousblk/setup-deno@v1

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test
